version: "3.9"
services:
  app:
    restart: always
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    expose:
      - "5000"

  db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local